version: "3.3"
services:
  db:
    image: mysql:5.7
    command: mysqld --init-file="/tmp/database/DB_Schema.sql"
    volumes:
      - ./database:/tmp/database
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: students_marks_manager
      MYSQL_USER: user
      MYSQL_PASSWORD: root

  web:
    depends_on:
      - db
    image: tomcat:8.5.78
    volumes:
      - ./StudentsMarksManager.war:/usr/local/tomcat/webapps/StudentsMarksManager.war
      - ./server.xml:/usr/local/tomcat/conf/server.xml
    ports:
      - "8888:8080"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: students_marks_manager
      MYSQL_USER: root
      MYSQL_PASSWORD: root
